const mongoose = require('mongoose');

const RegisteruserSchema = new mongoose.Schema({
  fullName:       { type: String, required: true },
  firstname:      { type: String },
  lastname:       { type: String },
  email:          { type: String, required: true, unique: true, lowercase: true },
  phone:          { type: String, required: true },
  altPhone:       { type: String, default: null },
  address:        { type: String, required: true },
  state:          { type: String, default: null },
  lga:            { type: String, default: null },
  dob:            { type: Date, required: true },
  gender:         { type: String, enum: ['m', 'f', 'o'] },
  accountType:    { type: String, enum: ['personal', 'business', 'corporate'], default: 'personal' },
  accountNumber:  { type: String, required: true, unique: true },
  branch:         { type: String, default: 'Main Branch' },
  password:       { type: String, required: true },
  transactionPin: { type: String, default: null },
  status:         { type: String, default: 'active' },
  frozenReason:   { type: String, default: null },
  pndType:        { type: String, enum: ['Debit', 'Full', null], default: null },
  createdAt:      { type: Date, default: Date.now },
  occupation:      { type: String, default: null },
  employer:        { type: String, default: null },
  employerAddress: { type: String, default: null },
  monthlyIncome:   { type: Number, default: 0 },
  pep:             { type: Boolean, default: false },
  currentComplianceTier: { type: Number, enum: [1, 2, 3], default: 1 },
  kycMetadata: {
    bvn:          { type: String, default: null },
    nin:          { type: String, default: null },
    utilityBill:  { type: String, default: null },
    verifiedAt:   { type: Date, default: null }
  },
  bvn:            { type: String, default: null },
  nin:            { type: String, default: null },
  kyc: {
    status:        { type: String, default: 'Pending' },
    level:         { type: String, default: 'Basic KYC' },
    completedDate: { type: Date, default: null },
    verifiedBy:    { type: String, default: null },
    bvnLinked:     { type: Boolean, default: false },
    ninLinked:     { type: Boolean, default: false },
    faceMatch:     { type: Boolean, default: false },
    documents:     { type: Array, default: [] },
  },
  interestRate:   { type: Number, default: 0 },
  interestEarned: { type: Number, default: 0 },
  balance:                { type: Number, default: 0.00 },
  investLiquidityBalance: { type: Number, default: 0.00 },
  currency:               { type: String, default: 'NGN' },
  watchlist:    { type: Boolean, default: false },
  amlFlag:      { type: Boolean, default: false },
  cbnBlacklist: { type: Boolean, default: false },
  dormant:      { type: Boolean, default: false },
  unclaimed:    { type: Boolean, default: false },
  crsFlag:      { type: Boolean, default: false },
  fatcaFlag:    { type: Boolean, default: false },
  failedLogins:    { type: Number, default: 0 },
  lastLogin:       { type: Date, default: null },
  loginDevice:     { type: String, default: null },
  loginIP:         { type: String, default: null },
  lastTransaction: { type: Date, default: null },
  smsAlert:   { type: Boolean, default: true },
  emailAlert: { type: Boolean, default: true },
  pushAlert:  { type: Boolean, default: true },
  transactionLimit: {
    daily:    { type: Number, default: 500000 },
    transfer: { type: Number, default: 200000 },
    pos:      { type: Number, default: 200000 },
    atm:      { type: Number, default: 100000 },
    ussd:     { type: Number, default: 100000 },
    nfc:      { type: Number, default: 20000 },
  },
  cardStatus: { type: String, enum: ['none', 'active', 'disabled'], default: 'none' },
  cardPin:    { type: String, default: null },
  card: {
    cardNumber: String,
    expiryDate: String,
    cvv:        String,
    tier:       { type: String, enum: ['silver', 'gold', 'black'] },
    address:    String,
    issuedAt:   { type: Date, default: Date.now },
  },
  mandates:    { type: Array, default: [] },
  signatories: { type: Array, default: [] },
  referral: {
    code:       { type: String, default: null },
    referredBy: { type: String, default: null },
    staffCode:  { type: String, default: null },
  },
  activeLoan: {
    id:             { type: String, default: null },
    principal:      { type: Number, default: 0 },
    totalRepayment: { type: Number, default: 0 },
    balance:        { type: Number, default: 0 },
    nextDue:        { type: String, default: null },
    textTenure:     { type: String, default: null },
    installment:    { type: Number, default: 0 }
  },
  myInvestments: [{
    name:       { type: String, required: true },
    principal:  { type: Number, required: true },
    interest:   { type: Number, default: 0 },
    rate:       { type: String, required: true },
    duration:   { type: Number, required: true },
    createdAt:  { type: Date, default: Date.now }
  }],
  completedInvestments: [{
    name:       { type: String, required: true },
    principal:  { type: Number, required: true },
    interest:   { type: Number, default: 0 },
    rate:       { type: String, required: true },
    duration:   { type: String, required: true },
    status:     { type: String, enum: ['Matured', 'Terminated', 'Withdrawn'], required: true },
    closedAt:   { type: Date, default: Date.now }
  }],
  investmentTransactions: [{
    txnId:  { type: String, required: true },
    type:   { type: String, enum: ['Investment Credit', 'Investment Debit', 'Emergency Withdrawal', 'Termination Layout Payout', 'Mature Payout', 'Asset Liquidation'], required: true },
    asset:  { type: String, required: true },
    amount: { type: Number, required: true },
    date:   { type: String, required: true }
  }]
});

module.exports = mongoose.model('Registeruser', RegisteruserSchema);